import type { Scenario } from './types';

/** Playable training scenarios for Board Sim. */
export const SCENARIOS: Scenario[] = [
  {
    id: 'morning-rush',
    title: 'Morning Rush',
    description:
      'Opening hour flood — walk-ins and waiters pile into Dispatch while advisors scramble. Spot W/R/S magnets and keep flow moving before bays clog.',
    durationMin: 45,
    realSecondsPerSimMin: 1.2,
    difficulty: 'intro',
    goals: {
      techHoursPerDay: 8,
      gpSoldTarget: 9000,
      gpPerHourHint: 150,
      flatRatePerFlagHr: 50,
      availableClockHrs: 8,
    },
    focus: 'Absorb opening flood; prioritize waiters without clogging bays',
    seedJobs: [
      {
        customerName: 'Maria Lopez',
        year: 2019,
        make: 'Honda',
        model: 'CR-V',
        column: 'dispatch',
        flags: ['urgent'],
        concern: 'Brake grind / safety',
        markers: ['W'],
        waiterTimerMin: 25,
        soldHours: 2.5,
        keysOnBoard: true,
        droppedAtSimMin: 0,
      
        inspectionStatus: 'not_started',
},
      {
        customerName: 'James Chen',
        year: 2016,
        make: 'Toyota',
        model: 'Camry',
        column: 'inspection',
        bay: 'Bay 2',
        tech: 'Derek',
        flags: [],
        concern: 'Check engine light',
        markers: ['R'],
        soldHours: 1.5,
      
        inspectionStatus: 'in_progress',
        repairLines: [
          {
            id: 'mr-jc-1',
            description: 'Diagnose CEL — P0420 catalyst efficiency',
            hours: 1.0,
            status: 'proposed',
          },
          {
            id: 'mr-jc-2',
            description: 'Replace downstream O2 sensor',
            hours: 0.5,
            partsNote: 'O2 sensor',
            status: 'proposed',
          },
        ],
},
      {
        customerName: 'Aisha Patel',
        year: 2021,
        make: 'Ford',
        model: 'F-150',
        column: 'approval',
        flags: ['waiting'],
        concern: 'Front suspension clunk',
        markers: ['S'],
        soldHours: 3.0,
      
        inspectionStatus: 'complete',
        answerDeliveredAtSimMin: 0,
        repairLines: [
          {
            id: 'mr-ap-1',
            description: 'Replace LF lower control arm',
            hours: 2.0,
            partsNote: 'Control arm + bushings',
            status: 'pending_approval',
          },
          {
            id: 'mr-ap-2',
            description: 'Alignment after suspension',
            hours: 1.0,
            status: 'pending_approval',
          },
          {
            id: 'mr-ap-3',
            description: 'Sway bar links (both)',
            hours: 0.8,
            partsNote: 'Sway links',
            status: 'approved',
            approvedAtSimMin: 0,
          },
        ],
},
      {
        customerName: 'Bob Miller',
        year: 2014,
        make: 'Chevy',
        model: 'Malibu',
        column: 'wip',
        bay: 'Bay 1',
        tech: 'Nina',
        flags: [],
        concern: 'Oil leak + filter housing',
        soldHours: 2.0,
      
        inspectionStatus: 'complete',
        answerDeliveredAtSimMin: 0,
        repairLines: [
          {
            id: 'mr-bm-1',
            description: 'Oil filter housing gasket',
            hours: 1.5,
            partsNote: 'Housing gasket kit',
            status: 'in_repair',
            approvedAtSimMin: 0,
          },
          {
            id: 'mr-bm-2',
            description: 'Oil + filter service',
            hours: 0.5,
            status: 'done',
            approvedAtSimMin: 0,
            completedAtSimMin: 0,
          },
        ],
},
    ],
    events: [
      {
        id: 'mr-1',
        atSimMin: 5,
        type: 'urgent_walkin',
        message: 'Walk-in: overheating SUV — customer waiting in lobby.',
        job: {
          customerName: 'Tyler Brooks',
          year: 2018,
          make: 'Jeep',
          model: 'Cherokee',
          column: 'dispatch',
          flags: ['urgent'],
          concern: 'Overheating / no A/C',
          markers: ['W'],
          waiterTimerMin: 20,
          soldHours: 1.8,
        },
      },
      {
        id: 'mr-2',
        atSimMin: 12,
        type: 'new_arrival',
        message: 'Tow-in arrives for morning appointment.',
        job: {
          customerName: 'Elena Soto',
          year: 2015,
          make: 'Nissan',
          model: 'Altima',
          column: 'dispatch',
          flags: [],
          concern: 'Won’t start — battery / starter',
          markers: ['R'],
          soldHours: 1.2,
        },
      },
      {
        id: 'mr-3',
        atSimMin: 20,
        type: 'customer_no_answer',
        message: 'Aisha Patel not answering — Approval stalled.',
        jobId: 'seed-2',
      },
      {
        id: 'mr-4',
        atSimMin: 30,
        type: 'qc_fail',
        message: 'QC fail on Malibu — road-test noise still present.',
        jobId: 'seed-3',
      },
      {
        id: 'mr-4b',
        atSimMin: 34,
        type: 'qc_rework',
        message: 'Advisor released Malibu QC fail back to Nina in WIP.',
        jobId: 'seed-3',
      },
      {
        id: 'mr-5',
        atSimMin: 36,
        type: 'new_arrival',
        message: 'Another drop-off before lunch.',
        job: {
          customerName: 'Chris Nguyen',
          year: 2020,
          make: 'Hyundai',
          model: 'Tucson',
          column: 'dispatch',
          flags: ['waiting'],
          concern: 'Alignment / tire wear',
          markers: ['W'],
          waiterTimerMin: 15,
          soldHours: 1.0,
        },
      },
    ],
  },
  {
    id: 'parts-delay',
    title: 'Parts Delay Chaos',
    description:
      'Supplier misses the morning truck. Jobs stack in Parts while WIP bays go idle. Clear blockers and re-sequence.',
    durationMin: 50,
    realSecondsPerSimMin: 1.2,
    difficulty: 'intermediate',
    goals: {
      techHoursPerDay: 8,
      gpSoldTarget: 13000,
      gpPerHourHint: 150,
      flatRatePerFlagHr: 50,
      availableClockHrs: 8,
    },
    focus: 'Clear parts blockers and re-sequence idle bays',
    seedJobs: [
      {
        customerName: 'Dana Wright',
        year: 2017,
        make: 'Subaru',
        model: 'Outback',
        column: 'parts',
        flags: ['blocked', 'waiting'],
        concern: 'Head gasket — waiting kit',
        markers: ['R'],
        soldHours: 8.0,
      
        inspectionStatus: 'complete',
        answerDeliveredAtSimMin: 0,
        repairLines: [
          {
            id: 'pd-dw-1',
            description: 'Head gasket kit + machine labor',
            hours: 6.0,
            partsNote: 'Head gasket kit',
            status: 'parts_ordered',
            partsEtaSimMin: 45,
            approvedAtSimMin: 0,
          },
          {
            id: 'pd-dw-2',
            description: 'Coolant flush after reseal',
            hours: 1.0,
            status: 'approved',
            approvedAtSimMin: 0,
          },
          {
            id: 'pd-dw-3',
            description: 'Timing cover reseal (related)',
            hours: 1.0,
            status: 'declined',
          },
        ],
},
      {
        customerName: 'Omar Haddad',
        year: 2019,
        make: 'Mazda',
        model: 'CX-5',
        column: 'parts',
        bay: 'Bay 3',
        tech: 'Kai',
        flags: ['waiting'],
        concern: 'Water pump + thermostat',
        soldHours: 4.5,
      
        inspectionStatus: 'complete',
        answerDeliveredAtSimMin: 0,
        repairLines: [
          {
            id: 'pd-oh-1',
            description: 'Water pump + thermostat',
            hours: 3.5,
            partsNote: 'Water pump / thermostat',
            status: 'parts_ordered',
            partsEtaSimMin: 25,
            approvedAtSimMin: 0,
          },
          {
            id: 'pd-oh-2',
            description: 'Drive belt',
            hours: 0.5,
            partsNote: 'Serpentine belt',
            status: 'parts_ready',
            approvedAtSimMin: 0,
          },
        ],
},
      {
        customerName: 'Lisa Park',
        year: 2022,
        make: 'Tesla',
        model: 'Model 3',
        column: 'inspection',
        bay: 'Bay 4',
        tech: 'Sam',
        flags: [],
        concern: 'Suspension noise EV',
        soldHours: 2.0,
      
        inspectionStatus: 'in_progress',
        repairLines: [
          {
            id: 'pd-lp-1',
            description: 'Road-test EV suspension noise',
            hours: 0.8,
            status: 'proposed',
          },
          {
            id: 'pd-lp-2',
            description: 'Control arm bushings (if confirmed)',
            hours: 2.0,
            partsNote: 'Bushing kit',
            status: 'proposed',
          },
        ],
},
      {
        customerName: 'Greg Foster',
        year: 2013,
        make: 'Ram',
        model: '1500',
        column: 'wip',
        bay: 'Bay 1',
        tech: 'Derek',
        flags: [],
        concern: 'Brake job in progress',
        soldHours: 2.5,
      
        inspectionStatus: 'complete',
        answerDeliveredAtSimMin: 0,
        repairLines: [
          {
            id: 'pd-gf-1',
            description: 'Front brake pads + rotors',
            hours: 2.0,
            status: 'in_repair',
            approvedAtSimMin: 0,
          },
          {
            id: 'pd-gf-2',
            description: 'Brake fluid flush',
            hours: 0.5,
            status: 'approved',
            approvedAtSimMin: 0,
          },
        ],
},
      {
        customerName: 'Nina Volkov',
        year: 2018,
        make: 'VW',
        model: 'Golf',
        column: 'approval',
        flags: [],
        concern: 'Timing chain estimate',
        markers: ['S'],
        soldHours: 6.0,
      
        inspectionStatus: 'complete',
        answerDeliveredAtSimMin: 0,
        repairLines: [
          {
            id: 'pd-nv-1',
            description: 'Timing chain kit',
            hours: 5.0,
            partsNote: 'Timing chain kit',
            status: 'pending_approval',
          },
          {
            id: 'pd-nv-2',
            description: 'Valve cover gaskets',
            hours: 1.5,
            status: 'pending_approval',
          },
        ],
},
    ],
    events: [
      {
        id: 'pd-1',
        atSimMin: 8,
        type: 'parts_late',
        message: 'Parts desk: Outback head-gasket kit delayed until afternoon.',
        jobId: 'seed-0',
      },
      {
        id: 'pd-2',
        atSimMin: 15,
        type: 'parts_late',
        message: 'CX-5 water pump backordered — tech idle.',
        jobId: 'seed-1',
      },
      {
        id: 'pd-3',
        atSimMin: 22,
        type: 'new_arrival',
        message: 'Quick-lube customer escalates to full inspection.',
        job: {
          customerName: 'Pat Rivera',
          year: 2016,
          make: 'Kia',
          model: 'Sorento',
          column: 'dispatch',
          flags: ['urgent'],
          concern: 'Oil change found coolant mix',
          markers: ['W'],
          waiterTimerMin: 18,
          soldHours: 1.5,
        },
      },
      {
        id: 'pd-4',
        atSimMin: 28,
        type: 'tech_unavailable',
        message: 'Kai called out sick — Bay 3 unassigned.',
        jobId: 'seed-1',
      },
      {
        id: 'pd-5',
        atSimMin: 38,
        type: 'qc_fail',
        message: 'Ram QC: uneven pad wear — redo one side.',
        jobId: 'seed-3',
      },
      {
        id: 'pd-6',
        atSimMin: 42,
        type: 'new_arrival',
        message: 'Dealer-overflow referral lands in Dispatch.',
        job: {
          customerName: 'Hank Ellis',
          year: 2020,
          make: 'GMC',
          model: 'Sierra',
          column: 'dispatch',
          flags: [],
          concern: 'Transmission shudder',
          soldHours: 3.0,
        },
      },
    ],
  },
  {
    id: 'advisor-bottleneck',
    title: 'Advisor Bottleneck',
    description:
      'Only one advisor on the floor. Approvals and dispatch stack up. Prioritize calls and keep techs fed.',
    durationMin: 40,
    realSecondsPerSimMin: 1.1,
    difficulty: 'intermediate',
    goals: {
      techHoursPerDay: 8,
      gpSoldTarget: 14000,
      gpPerHourHint: 150,
      flatRatePerFlagHr: 50,
      availableClockHrs: 8,
    },
    focus: 'Prioritize advisor calls; keep techs fed',
    seedJobs: [
      {
        customerName: 'Rachel Kim',
        year: 2019,
        make: 'BMW',
        model: '330i',
        column: 'approval',
        flags: ['waiting'],
        concern: 'Oil filter housing leak',
        markers: ['R'],
        soldHours: 3.5,
      
        inspectionStatus: 'complete',
        answerDeliveredAtSimMin: 0,
        repairLines: [
          {
            id: 'ab-rk-1',
            description: 'Oil filter housing replacement',
            hours: 2.5,
            partsNote: 'OFH assembly',
            status: 'pending_approval',
          },
          {
            id: 'ab-rk-2',
            description: 'Oil service after repair',
            hours: 0.5,
            status: 'pending_approval',
          },
          {
            id: 'ab-rk-3',
            description: 'Cabin filter',
            hours: 0.3,
            status: 'approved',
            approvedAtSimMin: 0,
          },
        ],
},
      {
        customerName: 'Steve Alvarez',
        year: 2015,
        make: 'Audi',
        model: 'Q5',
        column: 'approval',
        flags: ['waiting', 'urgent'],
        concern: 'Coolant leak — needs auth',
        markers: ['W'],
        waiterTimerMin: 22,
        soldHours: 2.8,
      
        inspectionStatus: 'complete',
        answerDeliveredAtSimMin: 0,
        repairLines: [
          {
            id: 'ab-sa-1',
            description: 'Water pump / coolant leak repair',
            hours: 2.8,
            partsNote: 'Water pump',
            status: 'pending_approval',
          },
        ],
},
      {
        customerName: 'Priya Shah',
        year: 2021,
        make: 'Toyota',
        model: 'RAV4',
        column: 'dispatch',
        flags: [],
        concern: 'Pre-purchase inspection',
        soldHours: 1.0,
      },
      {
        customerName: 'Mike Donovan',
        year: 2017,
        make: 'Honda',
        model: 'Accord',
        column: 'inspection',
        bay: 'Bay 2',
        tech: 'Nina',
        flags: [],
        concern: 'Vibration at highway speed',
        soldHours: 1.5,
      
        inspectionStatus: 'in_progress',
        repairLines: [
          {
            id: 'ab-md-1',
            description: 'Balance tires / check wheels',
            hours: 1.0,
            status: 'proposed',
          },
          {
            id: 'ab-md-2',
            description: 'Axle / CV inspection findings',
            hours: 0.5,
            status: 'proposed',
          },
        ],
},
      {
        customerName: 'Carla Diaz',
        year: 2014,
        make: 'Ford',
        model: 'Escape',
        column: 'qc',
        bay: 'Bay 1',
        tech: 'Derek',
        flags: [],
        concern: 'Alternator replacement',
        soldHours: 2.0,
      
        inspectionStatus: 'complete',
        answerDeliveredAtSimMin: 0,
        repairLines: [
          {
            id: 'ab-cd-1',
            description: 'Alternator replacement',
            hours: 2.0,
            status: 'done',
            approvedAtSimMin: 0,
            completedAtSimMin: 0,
          },
        ],
},
    ],
    events: [
      {
        id: 'ab-1',
        atSimMin: 4,
        type: 'customer_no_answer',
        message: 'Rachel Kim voicemail — Approval waiting.',
        jobId: 'seed-0',
      },
      {
        id: 'ab-2',
        atSimMin: 10,
        type: 'customer_no_answer',
        message: 'Steve Alvarez no-answer on urgent coolant auth.',
        jobId: 'seed-1',
      },
      {
        id: 'ab-3',
        atSimMin: 16,
        type: 'new_arrival',
        message: 'Phone booking wants same-day slot.',
        job: {
          customerName: 'Jordan Lee',
          year: 2018,
          make: 'Chevy',
          model: 'Equinox',
          column: 'dispatch',
          flags: ['waiting'],
          concern: 'A/C not cold',
          markers: ['S'],
          soldHours: 1.2,
        },
      },
      {
        id: 'ab-4',
        atSimMin: 24,
        type: 'qc_fail',
        message: 'Escape QC fail — charging voltage low again.',
        jobId: 'seed-4',
      },
      {
        id: 'ab-5',
        atSimMin: 32,
        type: 'urgent_walkin',
        message: 'Fleet van needs same-day LOF + inspection.',
        job: {
          customerName: 'Metro Fleet #12',
          year: 2020,
          make: 'Ford',
          model: 'Transit',
          column: 'dispatch',
          flags: ['urgent'],
          concern: 'Fleet LOF + multi-point',
          markers: ['W'],
          waiterTimerMin: 12,
          soldHours: 0.8,
        },
      },
    ],
  },
  {
    id: 'tech-capacity',
    title: 'Tech Capacity Crunch',
    description:
      'Two techs, too many cars in WIP/QC. Protect bay time, clear Final, and don’t starve Inspection.',
    durationMin: 45,
    realSecondsPerSimMin: 1.2,
    difficulty: 'advanced',
    goals: {
      techHoursPerDay: 8,
      gpSoldTarget: 20000,
      gpPerHourHint: 150,
      flatRatePerFlagHr: 50,
      availableClockHrs: 8,
    },
    focus: 'Protect bay time; clear Final before WIP piles up',
    seedJobs: [
      {
        customerName: 'Amy Torres',
        year: 2016,
        make: 'Jeep',
        model: 'Wrangler',
        column: 'wip',
        bay: 'Bay 1',
        tech: 'Derek',
        flags: [],
        concern: 'Transfer case leak',
        soldHours: 4.0,
      
        inspectionStatus: 'complete',
        answerDeliveredAtSimMin: 0,
        repairLines: [
          {
            id: 'tc-at-1',
            description: 'Transfer case reseal',
            hours: 3.5,
            partsNote: 'Seal kit',
            status: 'in_repair',
            approvedAtSimMin: 0,
          },
          {
            id: 'tc-at-2',
            description: 'Transfer case fluid',
            hours: 0.5,
            status: 'approved',
            approvedAtSimMin: 0,
          },
        ],
},
      {
        customerName: 'Ben Carter',
        year: 2019,
        make: 'Honda',
        model: 'Pilot',
        column: 'wip',
        bay: 'Bay 2',
        tech: 'Nina',
        flags: ['urgent'],
        concern: 'Timing belt due + leaks',
        markers: ['R'],
        soldHours: 6.5,
      
        inspectionStatus: 'complete',
        answerDeliveredAtSimMin: 0,
        repairLines: [
          {
            id: 'tc-bc-1',
            description: 'Timing belt + water pump',
            hours: 5.0,
            partsNote: 'Timing belt kit',
            status: 'in_repair',
            approvedAtSimMin: 0,
          },
          {
            id: 'tc-bc-2',
            description: 'Valve cover leaks',
            hours: 1.5,
            status: 'approved',
            approvedAtSimMin: 0,
          },
        ],
},
      {
        customerName: 'Zoe Martin',
        year: 2021,
        make: 'Subaru',
        model: 'Forester',
        column: 'qc',
        flags: [],
        concern: 'Brake package',
        soldHours: 2.5,
      
        inspectionStatus: 'complete',
        answerDeliveredAtSimMin: 0,
        repairLines: [
          {
            id: 'tc-zm-1',
            description: 'Front brake package',
            hours: 2.0,
            status: 'done',
            approvedAtSimMin: 0,
            completedAtSimMin: 0,
          },
          {
            id: 'tc-zm-2',
            description: 'Rear pads',
            hours: 1.0,
            status: 'done',
            approvedAtSimMin: 0,
            completedAtSimMin: 0,
          },
        ],
},
      {
        customerName: 'Ian Brooks',
        year: 2012,
        make: 'Toyota',
        model: 'Prius',
        column: 'parts',
        flags: ['waiting'],
        concern: 'Hybrid battery modules',
        soldHours: 5.0,
      
        inspectionStatus: 'complete',
        answerDeliveredAtSimMin: 0,
        repairLines: [
          {
            id: 'tc-ib-1',
            description: 'Hybrid battery modules',
            hours: 4.5,
            partsNote: 'Battery modules',
            status: 'parts_ordered',
            partsEtaSimMin: 55,
            approvedAtSimMin: 0,
          },
        ],
},
      {
        customerName: 'Kim Nakamura',
        year: 2018,
        make: 'Mazda',
        model: '3',
        column: 'inspection',
        flags: [],
        concern: 'Rattle on cold start',
        soldHours: 1.5,
      
        inspectionStatus: 'in_progress',
        repairLines: [
          {
            id: 'tc-kn-1',
            description: 'Cold-start rattle diagnosis',
            hours: 1.0,
            status: 'proposed',
          },
        ],
},
      {
        customerName: 'Drew Phillips',
        year: 2020,
        make: 'Ford',
        model: 'Explorer',
        column: 'dispatch',
        flags: [],
        concern: 'Recall + oil service',
        markers: ['S'],
        soldHours: 1.0,
      },
    ],
    events: [
      {
        id: 'tc-1',
        atSimMin: 6,
        type: 'tech_unavailable',
        message: 'Nina stuck on parts chase — Bay 2 stalled.',
        jobId: 'seed-1',
      },
      {
        id: 'tc-2',
        atSimMin: 14,
        type: 'qc_fail',
        message: 'Forester QC: pedal soft — bleed again.',
        jobId: 'seed-2',
      },
      {
        id: 'tc-3',
        atSimMin: 18,
        type: 'new_arrival',
        message: 'Warranty comeback returns to Dispatch.',
        job: {
          customerName: 'Sara Quinn',
          year: 2017,
          make: 'Chevy',
          model: 'Traverse',
          column: 'dispatch',
          flags: ['urgent', 'blocked'],
          concern: 'Comeback — same noise after prior visit',
          soldHours: 2.0,
        },
      },
      {
        id: 'tc-4',
        atSimMin: 26,
        type: 'parts_late',
        message: 'Prius modules still not on truck.',
        jobId: 'seed-3',
      },
      {
        id: 'tc-5',
        atSimMin: 34,
        type: 'urgent_walkin',
        message: 'No-start in the parking lot.',
        job: {
          customerName: 'Leo Grant',
          year: 2015,
          make: 'Nissan',
          model: 'Rogue',
          column: 'dispatch',
          flags: ['urgent'],
          concern: 'No-start — jump failed',
          markers: ['W'],
          waiterTimerMin: 10,
          soldHours: 1.0,
        },
      },
    ],
  },
  {
    id: 'comeback-day',
    title: 'Comeback Day',
    description:
      'Quality returns hit Dispatch while original WIP is still open. Protect bays from rework loops and don’t let comebacks stall the whole board.',
    durationMin: 48,
    realSecondsPerSimMin: 1.2,
    difficulty: 'advanced',
    goals: {
      techHoursPerDay: 8,
      gpSoldTarget: 19000,
      gpPerHourHint: 150,
      flatRatePerFlagHr: 50,
      availableClockHrs: 8,
    },
    focus: 'Break rework loops; shield bays from comebacks',
    seedJobs: [
      {
        customerName: 'Victor Ramos',
        year: 2017,
        make: 'Honda',
        model: 'Civic',
        column: 'dispatch',
        flags: ['urgent', 'blocked'],
        concern: 'Comeback — brake pulsation after pad job',
        markers: ['W', 'H'],
        waiterTimerMin: 20,
        soldHours: 2.0,
        keysOnBoard: true,
        droppedAtSimMin: 0,
      },
      {
        customerName: 'Helen Cho',
        year: 2019,
        make: 'Toyota',
        model: 'Highlander',
        column: 'dispatch',
        flags: ['urgent', 'blocked'],
        concern: 'Comeback — same knock after motor mount',
        markers: ['R'],
        soldHours: 3.0,
      },
      {
        customerName: 'Marcus Reed',
        year: 2015,
        make: 'Ford',
        model: 'Fusion',
        column: 'approval',
        flags: ['waiting'],
        concern: 'Comeback estimate — A/C recharge failed again',
        soldHours: 1.5,
      
        inspectionStatus: 'complete',
        answerDeliveredAtSimMin: 0,
        repairLines: [
          {
            id: 'cd-mr-1',
            description: 'A/C leak diagnosis + dye',
            hours: 1.0,
            status: 'pending_approval',
          },
          {
            id: 'cd-mr-2',
            description: 'Compressor if leak confirmed',
            hours: 3.0,
            partsNote: 'Compressor',
            status: 'proposed',
          },
        ],
},
      {
        customerName: 'Nora Blake',
        year: 2020,
        make: 'Subaru',
        model: 'Crosstrek',
        column: 'wip',
        bay: 'Bay 1',
        tech: 'Derek',
        flags: [],
        concern: 'Timing cover reseal (original RO)',
        soldHours: 4.0,
      
        inspectionStatus: 'complete',
        answerDeliveredAtSimMin: 0,
        repairLines: [
          {
            id: 'cd-nb-1',
            description: 'Timing cover reseal',
            hours: 4.0,
            status: 'in_repair',
            approvedAtSimMin: 0,
          },
        ],
},
      {
        customerName: 'Pete Alvarez',
        year: 2016,
        make: 'Chevy',
        model: 'Silverado',
        column: 'wip',
        bay: 'Bay 2',
        tech: 'Nina',
        flags: [],
        concern: 'Comeback rework — axle click still present',
        soldHours: 3.5,
      
        inspectionStatus: 'complete',
        answerDeliveredAtSimMin: 0,
        repairLines: [
          {
            id: 'cd-pa-1',
            description: 'Axle / CV click rework',
            hours: 3.0,
            status: 'in_repair',
            approvedAtSimMin: 0,
          },
        ],
},
      {
        customerName: 'Gina Torres',
        year: 2018,
        make: 'Mazda',
        model: 'CX-9',
        column: 'qc',
        bay: 'Bay 3',
        tech: 'Kai',
        flags: [],
        concern: 'Water pump replace — road test pending',
        soldHours: 3.0,
      },
    ],
    events: [
      {
        id: 'cd-1',
        atSimMin: 6,
        type: 'qc_fail',
        message: 'CX-9 QC fail — coolant weep at housing; back to advisor.',
        jobId: 'seed-5',
      },
      {
        id: 'cd-2',
        atSimMin: 12,
        type: 'urgent_walkin',
        message: 'Comeback walk-in: customer furious about recurring CEL.',
        job: {
          customerName: 'Andre Holt',
          year: 2014,
          make: 'Nissan',
          model: 'Pathfinder',
          column: 'dispatch',
          flags: ['urgent', 'blocked'],
          concern: 'Comeback — CEL returned 3 days after repair',
          markers: ['W'],
          waiterTimerMin: 15,
          soldHours: 2.5,
        },
      },
      {
        id: 'cd-3',
        atSimMin: 18,
        type: 'customer_no_answer',
        message: 'Marcus Reed no-answer on comeback A/C estimate.',
        jobId: 'seed-2',
      },
      {
        id: 'cd-4',
        atSimMin: 26,
        type: 'tech_unavailable',
        message: 'Nina pulled into comeback diagnosis — Silverado rework stalled.',
        jobId: 'seed-4',
      },
      {
        id: 'cd-5',
        atSimMin: 34,
        type: 'qc_fail',
        message: 'Crosstrek QC fail after reseal — oil seepage at corner.',
        jobId: 'seed-3',
      },
      {
        id: 'cd-6',
        atSimMin: 40,
        type: 'urgent_walkin',
        message: 'Another warranty return — noise after brake service.',
        job: {
          customerName: 'Paige Nguyen',
          year: 2021,
          make: 'Hyundai',
          model: 'Santa Fe',
          column: 'dispatch',
          flags: ['urgent', 'blocked'],
          concern: 'Comeback — grinding after recent brake package',
          soldHours: 2.0,
        },
      },
    ],
  },
  {
    id: 'promise-time',
    title: 'Promise Time Panic',
    description:
      'Afternoon pickup promises are stacking — waiters, rentals, and shuttles in the mix. Clear Final and QC before handoffs slip.',
    durationMin: 40,
    realSecondsPerSimMin: 1.0,
    difficulty: 'intermediate',
    goals: {
      techHoursPerDay: 8,
      gpSoldTarget: 12500,
      gpPerHourHint: 150,
      flatRatePerFlagHr: 50,
      availableClockHrs: 8,
    },
    focus: 'Clear Final/QC before promises; watch W+timer magnets',
    seedJobs: [
      {
        customerName: 'Olivia Hart',
        year: 2019,
        make: 'Honda',
        model: 'Pilot',
        column: 'qc',
        bay: 'Bay 1',
        tech: 'Derek',
        flags: [],
        concern: 'Brake package — promised 3:00 pickup',
        markers: ['W'],
        waiterTimerMin: 30,
        soldHours: 2.5,
      
        inspectionStatus: 'complete',
        answerDeliveredAtSimMin: 0,
        repairLines: [
          {
            id: 'pt-oh-1',
            description: 'Brake package — pads/rotors',
            hours: 2.5,
            status: 'done',
            approvedAtSimMin: 0,
            completedAtSimMin: 0,
          },
        ],
},
      {
        customerName: 'Ethan Cole',
        year: 2017,
        make: 'Toyota',
        model: 'Tacoma',
        column: 'qc',
        flags: [],
        concern: 'Alternator — promised 3:30',
        markers: ['R'],
        soldHours: 2.0,
      },
      {
        customerName: 'Maya Singh',
        year: 2020,
        make: 'Ford',
        model: 'Edge',
        column: 'final',
        flags: [],
        concern: 'LOF + cabin filter — waiting wash/handoff',
        markers: ['S'],
        soldHours: 0.8,
      },
      {
        customerName: 'Ryan Walsh',
        year: 2016,
        make: 'Jeep',
        model: 'Cherokee',
        column: 'final',
        flags: ['urgent'],
        concern: 'Battery + terminals — customer en route',
        markers: ['W'],
        waiterTimerMin: 8,
        soldHours: 1.0,
      },
      {
        customerName: 'Sofia Delgado',
        year: 2018,
        make: 'Subaru',
        model: 'Outback',
        column: 'wip',
        bay: 'Bay 2',
        tech: 'Nina',
        flags: [],
        concern: 'Wheel bearing almost done — 4:00 promise',
        markers: ['R'],
        soldHours: 2.2,
      
        inspectionStatus: 'complete',
        answerDeliveredAtSimMin: 0,
        repairLines: [
          {
            id: 'pt-sd-1',
            description: 'Wheel bearing (RF)',
            hours: 2.0,
            partsNote: 'Hub/bearing',
            status: 'in_repair',
            approvedAtSimMin: 0,
          },
        ],
},
      {
        customerName: 'Jake Morrow',
        year: 2015,
        make: 'Chevy',
        model: 'Equinox',
        column: 'wip',
        bay: 'Bay 3',
        tech: 'Kai',
        flags: [],
        concern: 'Front pads/rotors nearing completion',
        soldHours: 2.0,
      },
      {
        customerName: 'Claire Benton',
        year: 2021,
        make: 'Mazda',
        model: 'CX-5',
        column: 'dispatch',
        flags: [],
        concern: 'Late drop-off — soft appointment',
        soldHours: 1.0,
        keysOnBoard: true,
        droppedAtSimMin: 0,
      },
      {
        customerName: 'Tom Reeves',
        year: 2014,
        make: 'VW',
        model: 'Jetta',
        column: 'approval',
        flags: ['waiting'],
        concern: 'Last approval of the day — strut estimate',
        markers: ['W'],
        waiterTimerMin: 18,
        soldHours: 3.5,
      
        inspectionStatus: 'complete',
        answerDeliveredAtSimMin: 0,
        repairLines: [
          {
            id: 'pt-tr-1',
            description: 'Front struts (pair)',
            hours: 3.0,
            partsNote: 'Strut assemblies',
            status: 'pending_approval',
          },
          {
            id: 'pt-tr-2',
            description: 'Alignment',
            hours: 1.0,
            status: 'pending_approval',
          },
        ],
},
    ],
    events: [
      {
        id: 'pt-1',
        atSimMin: 5,
        type: 'new_arrival',
        message: 'Walk-in wants “just a quick look” — don’t steal bay time from promises.',
        job: {
          customerName: 'Brandon Pike',
          year: 2013,
          make: 'Nissan',
          model: 'Sentra',
          column: 'dispatch',
          flags: [],
          concern: 'Squeak when turning — not promised today',
          soldHours: 0.5,
        },
      },
      {
        id: 'pt-2',
        atSimMin: 14,
        type: 'qc_fail',
        message: 'Cherokee Final bounced — battery light still on after install.',
        jobId: 'seed-3',
      },
      {
        id: 'pt-3',
        atSimMin: 22,
        type: 'customer_no_answer',
        message: 'Tom Reeves no-answer on last Approval of the day.',
        jobId: 'seed-7',
      },
      {
        id: 'pt-4',
        atSimMin: 30,
        type: 'qc_fail',
        message: 'Pilot QC: pedal feel spongy — bleed before 3:00 promise.',
        jobId: 'seed-0',
      },
      {
        id: 'pt-5',
        atSimMin: 35,
        type: 'urgent_walkin',
        message: 'Late urgent walk-in — tow wants same-day slot.',
        job: {
          customerName: 'Irene Vargas',
          year: 2018,
          make: 'Kia',
          model: 'Sportage',
          column: 'dispatch',
          flags: ['urgent'],
          concern: 'Overheating on highway — no appointment',
          markers: ['W'],
          waiterTimerMin: 12,
          soldHours: 1.5,
        },
      },
    ],
  },
  {
    id: 'new-tech',
    title: 'New Tech Tuesday',
    description:
      'Jordan is new on Inspection and WIP. Senior Derek must cover slowdowns while QC fails climb — coach without starving the board.',
    durationMin: 50,
    realSecondsPerSimMin: 1.2,
    difficulty: 'intermediate',
    goals: {
      techHoursPerDay: 8,
      gpSoldTarget: 13500,
      gpPerHourHint: 150,
      flatRatePerFlagHr: 50,
      availableClockHrs: 8,
    },
    focus: 'Cover junior tech gaps; absorb extra QC fails',
    seedJobs: [
      {
        customerName: 'Hannah Brooks',
        year: 2019,
        make: 'Honda',
        model: 'HR-V',
        column: 'inspection',
        bay: 'Bay 2',
        tech: 'Jordan (new)',
        flags: [],
        concern: 'Multi-point + squeak under load',
        soldHours: 1.5,
      
        inspectionStatus: 'in_progress',
        repairLines: [
          {
            id: 'nt-hb-1',
            description: 'Multi-point findings — squeak under load',
            hours: 1.0,
            status: 'proposed',
          },
        ],
},
      {
        customerName: 'Luis Ortega',
        year: 2016,
        make: 'Toyota',
        model: 'Corolla',
        column: 'inspection',
        bay: 'Bay 4',
        tech: 'Jordan (new)',
        flags: ['waiting'],
        concern: 'Pre-purchase inspection — customer waiting',
        markers: ['W'],
        waiterTimerMin: 20,
        soldHours: 1.0,
      },
      {
        customerName: 'Diane Foster',
        year: 2017,
        make: 'Ford',
        model: 'Escape',
        column: 'wip',
        bay: 'Bay 1',
        tech: 'Derek',
        flags: [],
        concern: 'Timing chain / oil leaks (senior cover)',
        soldHours: 5.5,
      },
      {
        customerName: 'Kevin Park',
        year: 2020,
        make: 'Subaru',
        model: 'Impreza',
        column: 'parts',
        flags: ['waiting'],
        concern: 'Waiting rear pads + hardware',
        soldHours: 2.0,
      
        inspectionStatus: 'complete',
        answerDeliveredAtSimMin: 0,
        repairLines: [
          {
            id: 'nt-kp-1',
            description: 'Rear pads + hardware',
            hours: 1.5,
            partsNote: 'Rear pads + clips',
            status: 'parts_ordered',
            partsEtaSimMin: 35,
            approvedAtSimMin: 0,
          },
          {
            id: 'nt-kp-2',
            description: 'Brake fluid exchange',
            hours: 0.5,
            status: 'approved',
            approvedAtSimMin: 0,
          },
        ],
},
      {
        customerName: 'Amber Quinn',
        year: 2015,
        make: 'Chevy',
        model: 'Malibu',
        column: 'qc',
        flags: [],
        concern: 'Starter replace — Jordan’s first QC',
        soldHours: 1.8,
      },
      {
        customerName: 'Noah Ellis',
        year: 2018,
        make: 'Mazda',
        model: '6',
        column: 'wip',
        bay: 'Bay 3',
        tech: 'Jordan (new)',
        flags: [],
        concern: 'Brake job — junior tech on WIP',
        soldHours: 2.2,
      },
    ],
    events: [
      {
        id: 'nt-1',
        atSimMin: 7,
        type: 'tech_unavailable',
        message: 'Jordan stuck on HR-V diagnosis — needs senior help; Bay 2 stalled.',
        jobId: 'seed-0',
      },
      {
        id: 'nt-2',
        atSimMin: 15,
        type: 'qc_fail',
        message: 'Malibu QC fail — starter still intermittent after install.',
        jobId: 'seed-4',
      },
      {
        id: 'nt-3',
        atSimMin: 22,
        type: 'parts_late',
        message: 'Impreza pads delayed — parts desk missed the morning run.',
        jobId: 'seed-3',
      },
      {
        id: 'nt-4',
        atSimMin: 30,
        type: 'qc_fail',
        message: 'Mazda 6 QC fail — uneven torque on lug nuts; redo.',
        jobId: 'seed-5',
      },
      {
        id: 'nt-5',
        atSimMin: 38,
        type: 'new_arrival',
        message: 'Scheduled drop-off arrives while Jordan is still learning the board.',
        job: {
          customerName: 'Rita Gomez',
          year: 2021,
          make: 'Hyundai',
          model: 'Kona',
          column: 'dispatch',
          flags: [],
          concern: 'Alignment after tire purchase',
          markers: ['S'],
          soldHours: 1.0,
        },
      },
      {
        id: 'nt-6',
        atSimMin: 44,
        type: 'qc_fail',
        message: 'Escape second-look QC: residual oil weep — Derek must recheck.',
        jobId: 'seed-2',
      },
    ],
  },
  {
    id: 'weather-surge',
    title: 'Weather Surge',
    description:
      'Cold snap floods Dispatch with no-starts, waiters, and rentals. Triage W+timer drivers from deferred work before parts and QC chaos hit.',
    durationMin: 42,
    realSecondsPerSimMin: 1.2,
    difficulty: 'intro',
    goals: {
      techHoursPerDay: 8,
      gpSoldTarget: 8500,
      gpPerHourHint: 150,
      flatRatePerFlagHr: 50,
      availableClockHrs: 8,
    },
    focus: 'Triage waiters/rentals vs deferred cold-weather work',
    seedJobs: [
      {
        customerName: 'Carol Winters',
        year: 2015,
        make: 'Honda',
        model: 'Accord',
        column: 'dispatch',
        flags: ['urgent'],
        concern: 'No-start — dead battery, waiting in lobby',
        markers: ['W'],
        waiterTimerMin: 15,
        soldHours: 1.0,
      },
      {
        customerName: 'Doug Frost',
        year: 2012,
        make: 'Ford',
        model: 'Focus',
        column: 'dispatch',
        flags: ['urgent'],
        concern: 'No-start after overnight freeze',
        markers: ['W'],
        waiterTimerMin: 22,
        soldHours: 1.0,
      },
      {
        customerName: 'Becky Snow',
        year: 2018,
        make: 'Toyota',
        model: 'Camry',
        column: 'dispatch',
        flags: ['urgent'],
        concern: 'Battery light + slow crank',
        markers: ['R'],
        soldHours: 1.2,
      },
      {
        customerName: 'Alan Pierce',
        year: 2019,
        make: 'Subaru',
        model: 'Forester',
        column: 'inspection',
        bay: 'Bay 2',
        tech: 'Nina',
        flags: [],
        concern: 'Cold-start misfire diagnosis',
        soldHours: 2.0,
      },
      {
        customerName: 'Sheila Grant',
        year: 2016,
        make: 'Chevy',
        model: 'Equinox',
        column: 'approval',
        flags: ['waiting'],
        concern: 'Battery + alternator estimate waiting auth',
        markers: ['S'],
        soldHours: 2.5,
      
        inspectionStatus: 'complete',
        answerDeliveredAtSimMin: 0,
        repairLines: [
          {
            id: 'ws-sg-1',
            description: 'Battery replacement (AGM)',
            hours: 0.8,
            partsNote: 'AGM battery',
            status: 'pending_approval',
          },
          {
            id: 'ws-sg-2',
            description: 'Alternator if charging fails',
            hours: 2.0,
            partsNote: 'Alternator',
            status: 'proposed',
          },
        ],
},
      {
        customerName: 'Mitch Coleman',
        year: 2014,
        make: 'Nissan',
        model: 'Altima',
        column: 'qc',
        bay: 'Bay 1',
        tech: 'Derek',
        flags: [],
        concern: 'Quick battery job — rushed before surge',
        soldHours: 0.8,
      },
    ],
    events: [
      {
        id: 'ws-1',
        atSimMin: 3,
        type: 'urgent_walkin',
        message: 'Tow drops another no-start from the cold snap.',
        job: {
          customerName: 'Paula Keene',
          year: 2017,
          make: 'Kia',
          model: 'Soul',
          column: 'dispatch',
          flags: ['urgent'],
          concern: 'No-start — jump pack failed',
          markers: ['W'],
          waiterTimerMin: 12,
          soldHours: 1.0,
        },
      },
      {
        id: 'ws-2',
        atSimMin: 7,
        type: 'new_arrival',
        message: 'Appointment arrives mid-surge — deferred if needed.',
        job: {
          customerName: 'Greg Hale',
          year: 2020,
          make: 'Hyundai',
          model: 'Elantra',
          column: 'dispatch',
          flags: [],
          concern: 'Scheduled oil + cabin filter',
          soldHours: 0.7,
        },
      },
      {
        id: 'ws-3',
        atSimMin: 11,
        type: 'urgent_walkin',
        message: 'Fleet sedan won’t crank in the lot.',
        job: {
          customerName: 'City Fleet #7',
          year: 2019,
          make: 'Ford',
          model: 'Fusion',
          column: 'dispatch',
          flags: ['urgent'],
          concern: 'Fleet no-start — battery / cables',
          markers: ['R'],
          soldHours: 1.0,
        },
      },
      {
        id: 'ws-4',
        atSimMin: 20,
        type: 'parts_late',
        message: 'Battery supplier late — Camry and Focus waiting AGM stock.',
        jobId: 'seed-2',
      },
      {
        id: 'ws-5',
        atSimMin: 28,
        type: 'customer_no_answer',
        message: 'Sheila Grant no-answer on battery/alternator approval.',
        jobId: 'seed-4',
      },
      {
        id: 'ws-6',
        atSimMin: 34,
        type: 'qc_fail',
        message: 'Altima QC fail — rushed battery job; terminals loose / light returns.',
        jobId: 'seed-5',
      },
    ],
  },
  {
    id: 'waiter-timer',
    title: 'Waiter Timer Drill',
    description:
      'Lobby full of waiters with ticking clocks, plus rentals and shuttles. Prioritize W+timer without starving Parts/WIP — empty the bottleneck section.',
    durationMin: 35,
    realSecondsPerSimMin: 1.0,
    difficulty: 'intermediate',
    goals: {
      techHoursPerDay: 8,
      gpSoldTarget: 12000,
      gpPerHourHint: 150,
      flatRatePerFlagHr: 50,
      availableClockHrs: 8,
    },
    focus: 'Prioritize waiters (W+timer) without starving the rest',
    seedJobs: [
      {
        customerName: 'Lana Pierce',
        year: 2018,
        make: 'Honda',
        model: 'Civic',
        column: 'dispatch',
        flags: ['urgent'],
        concern: 'No-start — waiting in lobby',
        markers: ['W'],
        waiterTimerMin: 12,
        soldHours: 1.0,
        keysOnBoard: true,
        droppedAtSimMin: 0,
      },
      {
        customerName: 'Marco Diaz',
        year: 2016,
        make: 'Toyota',
        model: 'RAV4',
        column: 'dispatch',
        flags: ['urgent'],
        concern: 'Brake grind — customer watching clock',
        markers: ['W'],
        waiterTimerMin: 18,
        soldHours: 2.0,
      },
      {
        customerName: 'Jill Avery',
        year: 2020,
        make: 'Ford',
        model: 'Escape',
        column: 'inspection',
        bay: 'Bay 2',
        tech: 'Nina',
        flags: [],
        concern: 'Multi-point — rental car due back',
        markers: ['R'],
        soldHours: 1.5,
      },
      {
        customerName: 'Omar Blake',
        year: 2015,
        make: 'Chevy',
        model: 'Malibu',
        column: 'approval',
        flags: ['waiting'],
        concern: 'Estimate pending — shuttle booked',
        markers: ['S'],
        soldHours: 2.5,
      },
      {
        customerName: 'Tina Cho',
        year: 2019,
        make: 'Subaru',
        model: 'Impreza',
        column: 'parts',
        flags: ['waiting'],
        concern: 'Pads on order — sold hours parked',
        soldHours: 2.0,
        tech: 'Kai',
      
        inspectionStatus: 'complete',
        answerDeliveredAtSimMin: 0,
        repairLines: [
          {
            id: 'wt-tc-1',
            description: 'Front pads + rotors',
            hours: 2.0,
            partsNote: 'Pads/rotors',
            status: 'parts_ordered',
            partsEtaSimMin: 20,
            approvedAtSimMin: 0,
          },
        ],
},
      {
        customerName: 'Derek Holt',
        year: 2017,
        make: 'Mazda',
        model: 'CX-5',
        column: 'wip',
        bay: 'Bay 1',
        tech: 'Derek',
        flags: [],
        concern: 'Alternator nearly done',
        markers: ['W'],
        waiterTimerMin: 25,
        soldHours: 1.8,
      
        inspectionStatus: 'complete',
        answerDeliveredAtSimMin: 0,
        repairLines: [
          {
            id: 'wt-dh-1',
            description: 'Alternator replacement',
            hours: 1.8,
            status: 'in_repair',
            approvedAtSimMin: 0,
          },
        ],
},
      {
        customerName: 'Sam Rivera',
        year: 2014,
        make: 'Nissan',
        model: 'Altima',
        column: 'qc',
        bay: 'Bay 3',
        tech: 'Kai',
        flags: [],
        concern: 'Battery job — road test',
        markers: ['R'],
        soldHours: 0.8,
      },
    ],
    events: [
      {
        id: 'wt-1',
        atSimMin: 4,
        type: 'urgent_walkin',
        message: 'Another waiter walks in — timer starts now.',
        job: {
          customerName: 'Eva Quinn',
          year: 2021,
          make: 'Hyundai',
          model: 'Tucson',
          column: 'dispatch',
          flags: ['urgent'],
          concern: 'A/C dead — waiting with kids',
          markers: ['W'],
          waiterTimerMin: 15,
          soldHours: 1.2,
        },
      },
      {
        id: 'wt-2',
        atSimMin: 10,
        type: 'new_arrival',
        message: 'Shuttle drop-off arrives mid-drill.',
        job: {
          customerName: 'Paul Nguyen',
          year: 2018,
          make: 'Kia',
          model: 'Sorento',
          column: 'dispatch',
          flags: [],
          concern: 'Alignment — shuttle return window',
          markers: ['S'],
          soldHours: 1.0,
        },
      },
      {
        id: 'wt-3',
        atSimMin: 16,
        type: 'qc_fail',
        message: 'Altima QC fail — advisor must know before rework.',
        jobId: 'seed-6',
      },
      {
        id: 'wt-4',
        atSimMin: 20,
        type: 'parts_late',
        message: 'Impreza pads still out — hours stuck in Parts.',
        jobId: 'seed-4',
      },
      {
        id: 'wt-5',
        atSimMin: 24,
        type: 'qc_rework',
        message: 'Advisor released Altima back to Kai in WIP for QC rework.',
        jobId: 'seed-6',
      },
      {
        id: 'wt-6',
        atSimMin: 28,
        type: 'urgent_walkin',
        message: 'Rental return pressure — customer needs the car tonight.',
        job: {
          customerName: 'Fleet Rental #44',
          year: 2022,
          make: 'Toyota',
          model: 'Corolla',
          column: 'dispatch',
          flags: ['urgent'],
          concern: 'Rental LOF + wipers — return tonight',
          markers: ['R', 'W'],
          waiterTimerMin: 10,
          soldHours: 0.6,
        },
      },
    ],
  },
  {
    id: 'speed-zone',
    title: 'Speed Zone Drill',
    description:
      'Many waiters, 1-hour answer pressure, and keys still on the board. Protect the unsold speed zone — earliest timer first. Late answers punish the closing ratio.',
    durationMin: 50,
    realSecondsPerSimMin: 1.0,
    difficulty: 'advanced',
    goals: {
      techHoursPerDay: 8,
      gpSoldTarget: 21000,
      gpPerHourHint: 150,
      flatRatePerFlagHr: 50,
      availableClockHrs: 8,
    },
    focus: '1-hour answer / earliest timer; empty speed zone before sold work',
    seedJobs: [
      {
        customerName: 'Rita Hayes',
        year: 2019,
        make: 'Honda',
        model: 'CR-V',
        column: 'dispatch',
        flags: ['urgent'],
        concern: 'Brake grind — waiting in lobby',
        markers: ['W'],
        waiterTimerMin: 18,
        soldHours: 2.0,
        keysOnBoard: true,
        droppedAtSimMin: -50,
      },
      {
        customerName: 'Jon Park',
        year: 2016,
        make: 'Toyota',
        model: 'Camry',
        column: 'dispatch',
        flags: ['urgent'],
        concern: 'No-start — keys on magnet',
        markers: ['W'],
        waiterTimerMin: 28,
        soldHours: 1.2,
        keysOnBoard: true,
        droppedAtSimMin: -35,
      },
      {
        customerName: 'Elena Vos',
        year: 2020,
        make: 'Ford',
        model: 'Escape',
        column: 'dispatch',
        flags: [],
        concern: 'Check engine — drop-off unanswered',
        markers: ['W'],
        waiterTimerMin: 40,
        soldHours: 1.5,
        keysOnBoard: true,
        droppedAtSimMin: -20,
      },
      {
        customerName: 'Mike Chen',
        year: 2018,
        make: 'Subaru',
        model: 'Outback',
        column: 'inspection',
        bay: 'Bay 2',
        tech: 'Nina',
        flags: [],
        concern: 'Multi-point — answer not sold yet',
        markers: ['W'],
        waiterTimerMin: 22,
        soldHours: 1.8,
        droppedAtSimMin: -45,
        keysOnBoard: false,
      
        inspectionStatus: 'in_progress',
        repairLines: [
          {
            id: 'sz-mc-1',
            description: 'Multi-point — not sold yet',
            hours: 1.0,
            status: 'proposed',
          },
          {
            id: 'sz-mc-2',
            description: 'Cabin filter recommend',
            hours: 0.3,
            status: 'proposed',
          },
        ],
},
      {
        customerName: 'Sara Quinn',
        year: 2017,
        make: 'Chevy',
        model: 'Equinox',
        column: 'inspection',
        flags: [],
        concern: 'Alignment estimate pending answer',
        soldHours: 1.0,
        keysOnBoard: true,
        droppedAtSimMin: -10,
      },
      {
        customerName: 'Dan Ortiz',
        year: 2015,
        make: 'Nissan',
        model: 'Altima',
        column: 'approval',
        flags: ['waiting'],
        concern: 'Estimate waiting customer call-back',
        markers: ['S'],
        soldHours: 2.5,
        answerDeliveredAtSimMin: -5,
        droppedAtSimMin: -55,
      
        inspectionStatus: 'complete',
        repairLines: [
          {
            id: 'sz-do-1',
            description: 'Tune-up / plugs',
            hours: 1.5,
            status: 'pending_approval',
          },
          {
            id: 'sz-do-2',
            description: 'Intake gasket',
            hours: 2.0,
            status: 'pending_approval',
          },
        ],
},
      {
        customerName: 'Paula Reed',
        year: 2014,
        make: 'Mazda',
        model: 'CX-5',
        column: 'wip',
        bay: 'Bay 1',
        tech: 'Derek',
        flags: [],
        concern: 'Sold brake job — do not steal speed-zone time',
        soldHours: 2.2,
        answerDeliveredAtSimMin: -30,
        droppedAtSimMin: -90,
      
        inspectionStatus: 'complete',
        repairLines: [
          {
            id: 'sz-pr-1',
            description: 'Front brake job (sold)',
            hours: 2.2,
            status: 'in_repair',
            approvedAtSimMin: -30,
          },
        ],
},
      {
        customerName: 'Hank Lee',
        year: 2021,
        make: 'Hyundai',
        model: 'Tucson',
        column: 'parts',
        flags: ['waiting'],
        concern: 'Sold hours parked on parts — lower priority',
        soldHours: 3.0,
        tech: 'Kai',
        answerDeliveredAtSimMin: -40,
        droppedAtSimMin: -100,
      
        inspectionStatus: 'complete',
        repairLines: [
          {
            id: 'sz-hl-1',
            description: 'Control arms (sold — waiting parts)',
            hours: 3.0,
            partsNote: 'Control arms',
            status: 'parts_ordered',
            partsEtaSimMin: 40,
            approvedAtSimMin: -40,
          },
        ],
},
    ],
    events: [
      {
        id: 'sz-1',
        atSimMin: 4,
        type: 'urgent_walkin',
        message: 'Walk-in waiter — 1-hour clock starts now; keys on board.',
        job: {
          customerName: 'Tina Brooks',
          year: 2018,
          make: 'Jeep',
          model: 'Cherokee',
          column: 'dispatch',
          flags: ['urgent'],
          concern: 'Overheating — waiting with kids',
          markers: ['W'],
          waiterTimerMin: 20,
          soldHours: 1.5,
          keysOnBoard: true,
        },
      },
      {
        id: 'sz-2',
        atSimMin: 10,
        type: 'new_arrival',
        message: 'Drop-off lands in Dispatch — answer before the hour.',
        job: {
          customerName: 'Omar Diaz',
          year: 2019,
          make: 'Kia',
          model: 'Sportage',
          column: 'dispatch',
          flags: [],
          concern: 'Rattle on cold start',
          markers: ['W'],
          waiterTimerMin: 35,
          soldHours: 1.2,
          keysOnBoard: true,
        },
      },
      {
        id: 'sz-3',
        atSimMin: 16,
        type: 'customer_no_answer',
        message: 'Dan Ortiz still not answering — Approval stalled (selling zone).',
        jobId: 'seed-5',
      },
      {
        id: 'sz-4',
        atSimMin: 22,
        type: 'urgent_walkin',
        message: 'Another lobby waiter — earliest unanswered timer wins.',
        job: {
          customerName: 'Grace Kim',
          year: 2022,
          make: 'Toyota',
          model: 'RAV4',
          column: 'dispatch',
          flags: ['urgent'],
          concern: 'Battery light — waiting',
          markers: ['W', 'R'],
          waiterTimerMin: 15,
          soldHours: 1.0,
          keysOnBoard: true,
        },
      },
      {
        id: 'sz-5',
        atSimMin: 30,
        type: 'parts_late',
        message: 'Tucson parts delayed — sold work can wait; protect speed zone.',
        jobId: 'seed-7',
      },
      {
        id: 'sz-6',
        atSimMin: 38,
        type: 'qc_fail',
        message: 'CX-5 WIP QC bounce — advisor path, but do not abandon unanswered waiters.',
        jobId: 'seed-6',
      },
      {
        id: 'sz-7',
        atSimMin: 44,
        type: 'new_arrival',
        message: 'Late drop-off — still unsold until you deliver an answer.',
        job: {
          customerName: 'Leo Grant',
          year: 2013,
          make: 'Ford',
          model: 'Focus',
          column: 'dispatch',
          flags: [],
          concern: 'Soft appointment — keys on magnet',
          soldHours: 0.8,
          keysOnBoard: true,
        },
      },
    ],
  },
  {
    id: 'prod-meeting',
    title: 'Production Meeting Day',
    description:
      'Mid-morning production meeting stars today’s goes. Split an Approval stack, protect one heart comeback, and keep promised cars moving.',
    durationMin: 48,
    realSecondsPerSimMin: 1.1,
    difficulty: 'intermediate',
    goals: {
      techHoursPerDay: 8,
      gpSoldTarget: 14500,
      gpPerHourHint: 150,
      flatRatePerFlagHr: 50,
      availableClockHrs: 8,
    },
    focus: 'Production meeting commits; split Approval; heart comeback care',
    seedJobs: [
      {
        customerName: 'Amy Torres',
        year: 2018,
        make: 'Honda',
        model: 'Pilot',
        column: 'approval',
        flags: ['waiting'],
        concern: 'Brake package estimate — stack #1',
        markers: ['W'],
        waiterTimerMin: 25,
        soldHours: 2.5,
        answerDeliveredAtSimMin: 0,
        droppedAtSimMin: -15,
      
        inspectionStatus: 'complete',
        repairLines: [
          {
            id: 'pm-at-1',
            description: 'Brake package estimate',
            hours: 2.5,
            status: 'pending_approval',
          },
          {
            id: 'pm-at-2',
            description: 'Brake fluid flush',
            hours: 0.5,
            status: 'pending_approval',
          },
        ],
},
      {
        customerName: 'Ben Carter',
        year: 2016,
        make: 'Toyota',
        model: 'Highlander',
        column: 'approval',
        flags: ['waiting'],
        concern: 'Timing cover estimate — stack #2',
        markers: ['S'],
        soldHours: 4.0,
        answerDeliveredAtSimMin: 0,
        droppedAtSimMin: -25,
      
        inspectionStatus: 'complete',
        repairLines: [
          {
            id: 'pm-bc-1',
            description: 'Timing cover reseal estimate',
            hours: 4.0,
            status: 'pending_approval',
          },
        ],
},
      {
        customerName: 'Zoe Martin',
        year: 2019,
        make: 'Ford',
        model: 'Edge',
        column: 'approval',
        flags: ['waiting', 'urgent'],
        concern: 'Coolant leak auth — stack #3',
        soldHours: 2.8,
        answerDeliveredAtSimMin: 0,
        droppedAtSimMin: -40,
      
        inspectionStatus: 'complete',
        repairLines: [
          {
            id: 'pm-zm-1',
            description: 'Coolant leak / water pump auth',
            hours: 2.8,
            partsNote: 'Water pump',
            status: 'pending_approval',
          },
        ],
},
      {
        customerName: 'Ian Brooks',
        year: 2015,
        make: 'Subaru',
        model: 'Forester',
        column: 'wip',
        bay: 'Bay 1',
        tech: 'Derek',
        flags: [],
        concern: 'Sold water pump — likely today’s go',
        soldHours: 3.5,
        answerDeliveredAtSimMin: -20,
        droppedAtSimMin: -80,
      
        inspectionStatus: 'complete',
        repairLines: [
          {
            id: 'pm-ib-1',
            description: 'Water pump (sold)',
            hours: 3.5,
            status: 'in_repair',
            approvedAtSimMin: -20,
          },
        ],
},
      {
        customerName: 'Kim Nakamura',
        year: 2020,
        make: 'Mazda',
        model: 'CX-9',
        column: 'parts',
        tech: 'Kai',
        flags: ['waiting'],
        concern: 'Waiting pads — candidate for promise star',
        soldHours: 2.0,
        answerDeliveredAtSimMin: -10,
        droppedAtSimMin: -60,
      
        inspectionStatus: 'complete',
        repairLines: [
          {
            id: 'pm-kn-1',
            description: 'Rear pads',
            hours: 1.5,
            partsNote: 'Pads',
            status: 'parts_ordered',
            partsEtaSimMin: 30,
            approvedAtSimMin: -10,
          },
          {
            id: 'pm-kn-2',
            description: 'Hardware kit',
            hours: 0.3,
            status: 'parts_ordered',
            partsEtaSimMin: 30,
            approvedAtSimMin: -10,
          },
        ],
},
      {
        customerName: 'Drew Phillips',
        year: 2017,
        make: 'Chevy',
        model: 'Traverse',
        column: 'dispatch',
        flags: ['urgent', 'blocked'],
        concern: 'Heart comeback — same noise after prior visit',
        markers: ['H', 'W'],
        waiterTimerMin: 20,
        soldHours: 2.0,
        keysOnBoard: true,
        droppedAtSimMin: 0,
      },
      {
        customerName: 'Nora Blake',
        year: 2021,
        make: 'Hyundai',
        model: 'Santa Fe',
        column: 'inspection',
        bay: 'Bay 2',
        tech: 'Nina',
        flags: [],
        concern: 'Multi-point — not yet sold',
        soldHours: 1.2,
        keysOnBoard: false,
        droppedAtSimMin: -5,
      },
      {
        customerName: 'Pete Alvarez',
        year: 2014,
        make: 'Nissan',
        model: 'Rogue',
        column: 'qc',
        bay: 'Bay 3',
        tech: 'Kai',
        flags: [],
        concern: 'Alternator — road test pending',
        soldHours: 1.8,
        answerDeliveredAtSimMin: -35,
        droppedAtSimMin: -70,
      },
    ],
    events: [
      {
        id: 'pm-1',
        atSimMin: 8,
        type: 'customer_no_answer',
        message: 'Zoe Martin no-answer — Approval stack growing.',
        jobId: 'seed-2',
      },
      {
        id: 'pm-2',
        atSimMin: 14,
        type: 'production_meeting',
        message: 'Production meeting — commit today’s goes.',
        jobIds: ['seed-3', 'seed-4', 'seed-7'],
      },
      {
        id: 'pm-3',
        atSimMin: 20,
        type: 'new_arrival',
        message: 'Scheduled drop-off during meeting aftermath.',
        job: {
          customerName: 'Claire Benton',
          year: 2019,
          make: 'Honda',
          model: 'Accord',
          column: 'dispatch',
          flags: [],
          concern: 'Oil leak inspection',
          soldHours: 1.0,
          keysOnBoard: true,
        },
      },
      {
        id: 'pm-4',
        atSimMin: 26,
        type: 'qc_fail',
        message: 'Rogue QC fail — bounce to Approval.',
        jobId: 'seed-7',
      },
      {
        id: 'pm-5',
        atSimMin: 32,
        type: 'tech_unavailable',
        message: 'Kai pulled into heart diagnosis — pads job unassigned.',
        jobId: 'seed-4',
      },
      {
        id: 'pm-6',
        atSimMin: 38,
        type: 'qc_fail',
        message: 'Heart comeback hit QC path — manager/lead rework expected.',
        jobId: 'seed-5',
      },
      {
        id: 'pm-7',
        atSimMin: 42,
        type: 'urgent_walkin',
        message: 'Walk-in wants same-day — do not break promised stars.',
        job: {
          customerName: 'Fleet Van #3',
          year: 2020,
          make: 'Ford',
          model: 'Transit',
          column: 'dispatch',
          flags: ['urgent'],
          concern: 'Fleet LOF — not on today’s go list',
          markers: ['W'],
          waiterTimerMin: 12,
          soldHours: 0.8,
          keysOnBoard: true,
        },
      },
    ],
  },
];

export function getScenario(id: string): Scenario | undefined {
  return SCENARIOS.find((s) => s.id === id);
}
